### PR TITLE
WIP: ffmpeg compatibility

### PR DESCRIPTION
**Pull request by ymontmarin**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by ymontmarin** [comment]
@conda-forge-admin, please rerender

**Comment by traversaro** [comment]
If you plan to work on the feedstock, feel free to add yourself as a mantainer, thanks!

**Review by traversaro — APPROVED** [review]

**Comment by ymontmarin** [comment]
Start PR to arrive to a solution for https://github.com/conda-forge/openscenegraph-feedstock/issues/29

Long term project.

**Comment by ymontmarin** [comment]
This need not to be merged in this state, it has allowed to verify, that only the ffmpeg is needed to be fixed. A solution will be search for or it will be hard pin to 4.4

**Comment by ymontmarin** [comment]
It will never happen as openscenegraph is let down for vulkan. Meanwhile, we have https://github.com/conda-forge/ffmpeg-feedstock/pull/214

**Pull request closed without merging**
