### PR TITLE
Manual OSX ARM migration

### PR DESCRIPTION
**Pull request by traversaro**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
Like https://github.com/conda-forge/openscenegraph-feedstock/pull/18 but with an additional fix.

**Comment by traversaro** [comment]
The PR is ready for review @conda-forge/openscenegraph .

**Comment by jcarpent** [comment]
@traversaro What was the main issue?

**Comment by jcarpent** [comment]
Thanks a lot for porting to OSX ARM64.

**Comment by traversaro** [comment]
> @traversaro What was the main issue?

Some cmake projects use `try_run` in their CMake code to inspect the system. This is not possible when doing cross-compilation (unless you have an emulator of the target system, that we do not have for `osx-arm64`). So, you need to manually provide the results that the `try_run` would report. @wolfv provide this results in https://github.com/conda-forge/openscenegraph-feedstock/pull/18#issuecomment-1133066499 so we could set them.

**Comment by wolfv** [comment]
Thanks @traversaro!

**Pull request merged**
